// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gixamxmxqmhisvomvicz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdpeGFteG14cW1oaXN2b212aWN6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE1NjA1NDIsImV4cCI6MjA1NzEzNjU0Mn0.hy-IV0Nc2i7Ogt-GZA-ZtgvuarGMKv7VyqQ_VTOEAU4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);